[workspace]
resolver = "2"
members = [
  "crates/runner-cli",
  "crates/runner-core",
  "crates/runner-app",
  "crates/runner-infra",
  "crates/runner-plugins",
  "crates/xtask",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/fzf54122/neo-runner"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "time"] }
tracing = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
rusqlite = { version = "0.32", features = ["bundled"] }

[profile.release]
opt-level = "z"     # 或 "s"，z 更极致体积
lto = true          # Link Time Optimization
codegen-units = 1   # 减少分块编译，利于优化
panic = "abort"     # 不保留 unwind 代码
strip = true        # 直接 strip 符号（新版本 cargo 支持）
